### ISSUE TITLE
Allow access to original http Request in WebSocket handler

### ISSUE THREAD

**Issue by emeyex** [dart-lang/shelf_web_socket#17]
Right now, AFAICT there's not a great way to reference the original HTTP request (url, headers, etc) inside of the user-supplied WebSocket handler. I had a look to see if I could pass it through, but given that it might change the underlying signature of `webSocketHandler` or its expected `onConnection` callback, I thought it best to discuss if this was a feasible addition, and direction on desired implementation.

**Comment by emeyex** [comment]
Closing, as I discovered that `request.context['shelf.io.connection_info']` contains the `HttpConnectionInfo` that I was interested in.

**Comment by bmsrangel** [comment]
@adriano-moreira it worked! Thank you so so much, man!!! Seriously, I was already giving up on it! Thank you very much!
