### ISSUE TITLE
Not supported the web platform

### ISSUE THREAD

**Issue by airk000** [dart-lang/shelf_web_socket#22]
```
Skipping compiling web_socket_demo|lib/main_web_entrypoint.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:

shelf|lib/shelf_io.dart
shelf|lib/src/io_server.dart

```

While I'm using this library to build a web application, the message above came out.

So, is the problem cause by "dart:io"?

**Comment by natebosch** [comment]
`shelf` doesn't support the web at all, I'm not sure what your goal is. Can you clarify?

> So, is the problem cause by "dart:io"?

yes, `dart:io` is not supported at all on the web.

**Comment by airk000** [comment]
😂Sorry, I did know few about the WebSocket. I just wanted to build a WebSocket server in the Chrome, now... after more reading and practice, emm... it sounds like a little bit stupid. I've use the tool in the wrong way, my fault.
