### ISSUE TITLE
The method 'WebSocketChannel' isn't defined for the class 'WebSocketHandler'.

### ISSUE THREAD

**Issue by pishguy** [dart-lang/shelf_web_socket#37]
```
/F:/android/flutter/.pub-cache/hosted/pub.dartlang.org/shelf_web_socket-1.0.1/lib/src/web_socket_handler.dart:82:11: Error: The m
ethod 'WebSocketChannel' isn't defined for the class 'WebSocketHandler'.
 - 'WebSocketHandler' is from 'package:shelf_web_socket/src/web_socket_handler.dart' ('/F:/android/flutter/.pub-cache/hosted/pub.
dartlang.org/shelf_web_socket-1.0.1/lib/src/web_socket_handler.dart').
Try correcting the name to the name of an existing method, or defining a method named 'WebSocketChannel'.
          WebSocketChannel(channel, pingInterval: _pingInterval), protocol);
          ^^^^^^^^^^^^^^^^
[INFO] Precompiling build script... completed, took 2.1s
```

**Comment by natebosch** [comment]
Did you make any edits in your pub cache?

The class `WebSocketChannel` is from `package:web_socket_channel/web_socket_channel.dart` and that hasn't changed recently.

Do you have full reproduction steps?

**Comment by pezi** [comment]
Version 1.0.1 is broken out out the box.

I added this version to my project - added the exmample code to my project and this results in the resolving erros of the TO. Going back to 1.0.0 solves the problem.

**Comment by natebosch** [comment]
There are no differences between `1.0.0` and `1.0.1` that would cause the import of `WebSocketChannel` to stop working.

There could also be a local edit to `web_socket_channel` in your pub cache causing this. a `flutter pub cache repair` might resolve the issue.

**Comment by pezi** [comment]
I upgrade to the last version - now it works. Thanks for your support.
